// Rótulos PT-BR (vocabulário de academia) dos valores fixos do ExerciseDB.
export const bodyPartLabels: Record<string, string> = {
  neck: "Pescoço",
  "lower arms": "Antebraço",
  shoulders: "Ombros",
  cardio: "Cardio",
  "upper arms": "Braços",
  chest: "Peito",
  "lower legs": "Panturrilha",
  back: "Costas",
  "upper legs": "Pernas",
  waist: "Abdômen",
};

export const equipmentLabels: Record<string, string> = {
  "stepmill machine": "Simulador de escada",
  "elliptical machine": "Elíptico",
  "trap bar": "Barra hexagonal",
  tire: "Pneu",
  "stationary bike": "Bicicleta ergométrica",
  "ab wheel": "Roda abdominal",
  "smith machine": "Smith",
  hammer: "Marreta",
  "ski ergometer": "Ergômetro de esqui",
  roller: "Rolo",
  "resistance band": "Elástico",
  "bosu ball": "Bosu",
  weighted: "Anilha/peso extra",
  "olympic barbell": "Barra olímpica",
  kettlebell: "Kettlebell",
  "upper body ergometer": "Ergômetro de braços",
  "sled machine": "Trenó",
  "EZ bar": "Barra W",
  dumbbell: "Halteres",
  rope: "Corda",
  barbell: "Barra",
  "stability ball": "Bola suíça",
  "medicine ball": "Medicine ball",
  assisted: "Assistido",
  "leverage machine": "Máquina",
  cable: "Cabo",
  bodyweight: "Peso corporal",
  towel: "Toalha",
  "tennis ball": "Bola de tênis",
  "suspension trainer": "Suspensão (TRX)",
};

export const muscleLabels: Record<string, string> = {
  "tibialis anterior": "Tibial anterior",
  hands: "Mãos",
  sternocleidomastoid: "Esternocleidomastoideo",
  soleus: "Sóleo",
  adductors: "Adutores",
  abdominals: "Abdominais",
  "grip muscles": "Músculos da pegada",
  "wrist extensors": "Extensores do punho",
  "wrist flexors": "Flexores do punho",
  "latissimus dorsi": "Dorsais",
  pectorals: "Peitorais",
  "rotator cuff": "Manguito rotador",
  wrists: "Punhos",
  brachialis: "Braquial",
  deltoids: "Deltoides",
  feet: "Pés",
  ankles: "Tornozelos",
  trapezius: "Trapézio",
  "rear deltoids": "Deltoide posterior",
  quadriceps: "Quadríceps",
  back: "Costas",
  core: "Core",
  "ankle stabilizers": "Estabilizadores do tornozelo",
  rhomboids: "Romboides",
  obliques: "Oblíquos",
  "erector spinae": "Eretores da espinha",
  "hip flexors": "Flexores do quadril",
  "levator scapulae": "Levantador da escápula",
  abductors: "Abdutores",
  "serratus anterior": "Serrátil anterior",
  forearms: "Antebraços",
  biceps: "Bíceps",
  "upper back": "Parte superior das costas",
  "cardiovascular system": "Sistema cardiovascular",
  triceps: "Tríceps",
  hamstrings: "Posteriores de coxa",
  glutes: "Glúteos",
  calves: "Panturrilhas",
};

export type Labelled = { value: string; label: string };

const capitalize = (v: string) => v.charAt(0).toUpperCase() + v.slice(1);

export const label = (dict: Record<string, string>, value: string): Labelled => ({
  value,
  label: dict[value] ?? capitalize(value),
});
